language: php

php:
- 7.0
- 7.1
sudo: false

before_install:
- openssl aes-256-cbc -K $encrypted_cf65f30c8215_key -iv $encrypted_cf65f30c8215_iv
  -in deploy_rsa.enc -out deploy_rsa -d

install:
- travis_retry composer install

before_script:
- mkdir -p storage/framework/{cache,views,sessions}
- cp .env.travis .env
- php artisan key:generate
- php artisan cache:clear
- php artisan config:clear
- php artisan view:clear
- php artisan clear-compiled

deploy:
- provider: script
  skip_cleanup: true
  script: ./deploy.sh
  on:
    branch: master

notifications:
  email: false
